name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  codeQuality:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit test
      run: pytest
